### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by faseidl** [martin-experiments/google-recaptcha#1]
If the response from https://www.google.com/recaptcha/api/siteverify does not contain body['error-codes'], handleResponse() throws a type error on line 52:

```
new Error(`Failed to verify: ${body['error-codes'].join(', ')}`)
```

**Comment by umamialex** [comment]
@faseidl Thanks for reporting! v1.1.0 is now published.

**Comment by faseidl** [comment]
Thanks for the quick fix!
  -- Andy
